const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const context=vm.createContext({});
vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../js/canh-dong-sinh-thai-art.js'),'utf8'),context);
const art=context.HeSinhThaiArt;
assert.equal(art.habitat('giai-doan-ma').type,'dragonfly');
assert.equal(art.habitat('lam-dong').stage,'booting');
assert.equal(art.habitat('tro-bong').stage,'heading');
assert.equal(art.habitat('chac-hat').stage,'filling');
assert.equal(art.habitat('chin-vang').stage,'ripe');
assert.equal(art.habitat('com-moi').stage,'stubble');
assert(art.riceSpec.seedling.height<art.riceSpec.tillering.height);
assert(art.riceSpec.tillering.tillers>art.riceSpec.seedling.tillers);
const crab=art.crabPose;
assert.notEqual(crab(0).x,crab(4).x,'Crab crosses the bank');
assert.equal(crab(0).phase,'walk');
assert.notEqual(crab(.2).frame,crab(.4).frame,'Walking legs alternate');
const snake=art.snakePose;
assert.equal(snake(0).frame,0);
assert(snake(2).frame>snake(0).frame,'Snake uncoils as it crawls');
assert.notEqual(snake(0).x,snake(3).x);
const hopper=art.grasshopperPose;
assert.equal(hopper(.5,0).phase,'crouch');
assert.equal(hopper(1.1,0).phase,'push');
assert.equal(hopper(1.9,0).phase,'air');
assert(hopper(1.9,0).y<hopper(.5,0).y,'Leg push lifts the grasshopper');
assert.equal(hopper(2.7,0).phase,'land');
assert.equal(hopper(3.1,0).phase,'rest');
for(let i=0;i<5;i++)assert(hopper(0,i).x>=35&&hopper(0,i).x<290,'Five insects fit the scene');
const perched=art.dragonflyPose(1,0,'seedling'),landed=art.dragonflyPose(12,0,'seedling');
assert(perched.perched&&landed.perched);
assert(Math.abs(perched.x-landed.x)<7);assert.equal(perched.y,landed.y);
assert(!art.dragonflyPose(6,0,'seedling').perched);
assert(art.dragonflyPose(6,0,'seedling').y<perched.y);
assert(art.mousePose(1).run);assert(!art.mousePose(4).run);
assert.equal(art.mousePose(3).x,art.mousePose(5).x,'Nibbling stays at the rice base');
assert(art.mousePose(8).run);
for(let t=0;t<20;t+=.1){
 const a=art.duckPose(t),b=art.duckPose(t,1);
 assert(Math.abs(a.y-b.y)>13,'Duckling swims in a separate lane');
 for(const p of [a,b])assert(p.x>35&&p.x<285);
}
console.log('Rice stages, snake slither, crab walking legs, five staggered jumps and separate duck lanes passed.');
